// <auto-generated />
using System;
using DbOptimizer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbOptimizer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DbOptimizerDbContext))]
    [Migration("20260417151135_AddMafWorkflowFields")]
    partial class AddMafWorkflowFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.AgentExecutionEntity", b =>
                {
                    b.Property<Guid>("ExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_name");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ExecutorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("executor_name");

                    b.Property<string>("InputData")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_data");

                    b.Property<string>("OutputData")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_data");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TokenUsage")
                        .HasColumnType("jsonb")
                        .HasColumnName("token_usage");

                    b.HasKey("ExecutionId");

                    b.HasIndex("AgentName")
                        .HasDatabaseName("idx_agent_executions_agent_name");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_agent_executions_session_id");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_agent_executions_started_at_desc");

                    b.ToTable("agent_executions", (string)null);
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.AgentMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("MessageId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_agent_messages_created_at_desc");

                    b.HasIndex("ExecutionId")
                        .HasDatabaseName("idx_agent_messages_execution_id");

                    b.ToTable("agent_messages", (string)null);
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.DecisionRecordEntity", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("decision_type");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reasoning");

                    b.HasKey("DecisionId");

                    b.HasIndex("DecisionType")
                        .HasDatabaseName("idx_decision_records_decision_type");

                    b.HasIndex("ExecutionId")
                        .HasDatabaseName("idx_decision_records_execution_id");

                    b.ToTable("decision_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_decision_records_confidence_range", "confidence >= 0 AND confidence <= 100");
                        });
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.ErrorLogEntity", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Context")
                        .HasColumnType("jsonb")
                        .HasColumnName("context");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("error_type");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.HasKey("LogId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_error_logs_created_at_desc");

                    b.HasIndex("ErrorType")
                        .HasDatabaseName("idx_error_logs_error_type");

                    b.HasIndex("ExecutionId")
                        .HasDatabaseName("idx_error_logs_execution_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_error_logs_session_id");

                    b.ToTable("error_logs", (string)null);
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.PromptVersionEntity", b =>
                {
                    b.Property<Guid>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("version_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_template");

                    b.Property<string>("Variables")
                        .HasColumnType("jsonb")
                        .HasColumnName("variables");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("VersionId");

                    b.HasIndex("AgentName", "IsActive")
                        .HasDatabaseName("idx_prompt_versions_agent_name_active");

                    b.HasIndex("AgentName", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_prompt_versions_agent_version");

                    b.ToTable("prompt_versions", (string)null);
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.ReviewTaskEntity", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("task_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Adjustments")
                        .HasColumnType("jsonb")
                        .HasColumnName("adjustments");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EngineCheckpointRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("engine_checkpoint_ref");

                    b.Property<string>("EngineRunId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("engine_run_id");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewerComment")
                        .HasColumnType("text")
                        .HasColumnName("reviewer_comment");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_type");

                    b.HasKey("TaskId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_review_tasks_created_at_desc");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("idx_review_tasks_request_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_review_tasks_session_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_review_tasks_status");

                    b.HasIndex("TaskType")
                        .HasDatabaseName("idx_review_tasks_task_type");

                    b.ToTable("review_tasks", (string)null);
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.SlowQueryEntity", b =>
                {
                    b.Property<Guid>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("query_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<TimeSpan>("AvgExecutionTime")
                        .HasColumnType("interval")
                        .HasColumnName("avg_execution_time");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DatabaseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("database_id");

                    b.Property<string>("DatabaseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("database_type");

                    b.Property<int>("ExecutionCount")
                        .HasColumnType("integer")
                        .HasColumnName("execution_count");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid?>("LatestAnalysisSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_analysis_session_id");

                    b.Property<TimeSpan>("MaxExecutionTime")
                        .HasColumnType("interval")
                        .HasColumnName("max_execution_time");

                    b.Property<string>("OriginalSql")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_sql");

                    b.Property<string>("QueryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("query_hash");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("query_type");

                    b.Property<string>("SqlFingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql_fingerprint");

                    b.Property<string>("Tables")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tables");

                    b.Property<long>("TotalRowsExamined")
                        .HasColumnType("bigint")
                        .HasColumnName("total_rows_examined");

                    b.Property<long>("TotalRowsSent")
                        .HasColumnType("bigint")
                        .HasColumnName("total_rows_sent");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("QueryId");

                    b.HasIndex("AvgExecutionTime")
                        .IsDescending()
                        .HasDatabaseName("idx_slow_queries_avg_time_desc");

                    b.HasIndex("DatabaseId")
                        .HasDatabaseName("idx_slow_queries_database_id");

                    b.HasIndex("LastSeenAt")
                        .IsDescending()
                        .HasDatabaseName("idx_slow_queries_last_seen_desc");

                    b.HasIndex("LatestAnalysisSessionId")
                        .HasDatabaseName("idx_slow_queries_latest_analysis_session_id");

                    b.HasIndex("QueryHash", "DatabaseId")
                        .HasDatabaseName("idx_slow_queries_hash_db");

                    b.ToTable("slow_queries", (string)null);
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.ToolCallEntity", b =>
                {
                    b.Property<Guid>("CallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("call_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("arguments");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tool_name");

                    b.HasKey("CallId");

                    b.HasIndex("ExecutionId")
                        .HasDatabaseName("idx_tool_calls_execution_id");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_tool_calls_started_at_desc");

                    b.HasIndex("ToolName")
                        .HasDatabaseName("idx_tool_calls_tool_name");

                    b.ToTable("tool_calls", (string)null);
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.WorkflowSessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EngineCheckpointRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("engine_checkpoint_ref");

                    b.Property<string>("EngineRunId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("engine_run_id");

                    b.Property<string>("EngineState")
                        .HasColumnType("jsonb")
                        .HasColumnName("engine_state");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("maf")
                        .HasColumnName("engine_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ResultType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("result_type");

                    b.Property<Guid?>("SourceRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_ref_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("manual")
                        .HasColumnName("source_type");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workflow_type");

                    b.HasKey("SessionId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_workflow_sessions_created_at_desc");

                    b.HasIndex("ResultType")
                        .HasDatabaseName("idx_workflow_sessions_result_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_workflow_sessions_status");

                    b.HasIndex("WorkflowType")
                        .HasDatabaseName("idx_workflow_sessions_workflow_type");

                    b.ToTable("workflow_sessions", (string)null);
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.AgentExecutionEntity", b =>
                {
                    b.HasOne("DbOptimizer.Infrastructure.Persistence.WorkflowSessionEntity", "Session")
                        .WithMany("AgentExecutions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.AgentMessageEntity", b =>
                {
                    b.HasOne("DbOptimizer.Infrastructure.Persistence.AgentExecutionEntity", "Execution")
                        .WithMany("AgentMessages")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.DecisionRecordEntity", b =>
                {
                    b.HasOne("DbOptimizer.Infrastructure.Persistence.AgentExecutionEntity", "Execution")
                        .WithMany("DecisionRecords")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.ErrorLogEntity", b =>
                {
                    b.HasOne("DbOptimizer.Infrastructure.Persistence.AgentExecutionEntity", "Execution")
                        .WithMany("ErrorLogs")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DbOptimizer.Infrastructure.Persistence.WorkflowSessionEntity", "Session")
                        .WithMany("ErrorLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Execution");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.ReviewTaskEntity", b =>
                {
                    b.HasOne("DbOptimizer.Infrastructure.Persistence.WorkflowSessionEntity", "Session")
                        .WithMany("ReviewTasks")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.ToolCallEntity", b =>
                {
                    b.HasOne("DbOptimizer.Infrastructure.Persistence.AgentExecutionEntity", "Execution")
                        .WithMany("ToolCalls")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.AgentExecutionEntity", b =>
                {
                    b.Navigation("AgentMessages");

                    b.Navigation("DecisionRecords");

                    b.Navigation("ErrorLogs");

                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("DbOptimizer.Infrastructure.Persistence.WorkflowSessionEntity", b =>
                {
                    b.Navigation("AgentExecutions");

                    b.Navigation("ErrorLogs");

                    b.Navigation("ReviewTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
